apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonjune
spec:
  replicas: 3  # 복제본 2개
  selector:
    matchLabels:
      app: wonjune
  template:
    metadata:
      labels:
        app: wonjune
    spec:
      containers:
      - name: wonjune-web
        image: wonjune:0913
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred


#로드 밸런서 작성하기
---
apiVersion: v1
kind: Service
metadata:
  name: wonjune-svc
spec:
  selector:
    app: wonjune
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
